### ISSUE TITLE
Camera image is missing

### ISSUE THREAD

**Issue by vr2045** [openhsi/openhsi#23] opened 2022-01-29 17:51 UTC
**Describe the bug**
See title

**Comment by christhechris** [comment] 2022-01-29 22:19
Hi @vr2045 ,
Could you elaborate? What are you doing to acquire and view an image?

**Comment by YiweiMao** [comment] 2022-02-08 03:05
This is too vague to decipher what the bug is. Can you provide the code snippet or minimal example that is causing this error? 
We'll close this issue if there isn't any else in the next few days.

**Comment by christhechris** [comment] 2022-02-08 03:14
(And/or if this is to do with Robotx OprnHSI)

**Comment by vr2045** [comment] 2022-02-08 03:24
Apologize for the vague description.
There is no picture of the camera on the main page.

**Comment by YiweiMao** [comment] 2022-02-09 11:24
The main page for our documentation https://openhsi.github.io/openhsi/ is rendering correctly with a picture of an OpenHSI camera (not the one for RobotX). 
By main page, do you mean this Github repository? (The README.md file is autogenerated from notebooks and not all HTML content carries over) I can see a missing link to a photo in README.md that is fine in the docs. I'll see about fixing this in the next patch so thanks for bringing it up. 
If it's something else, please include a screenshot showing the cause of the issue. Main page is bit vague but I hope I'm understanding you correctly.

**Closed** 2022-03-01 10:54 UTC
Labels: question
